import type { SpeciesDef } from "./types"

export const SPECIES: SpeciesDef[] = [
  {
    id: 0,
    name: "Люди",
    plural: "людей",
    color: "#c9a24b",
    might: 1.0,
    cunning: 0.7,
    fertility: 1.15,
    industry: 1.1,
    aggression: 0.45,
    leaderNames: ["Альдрик", "Гарольд", "Седрик", "Ричмонд", "Освальд", "Бертран"],
    princessNames: ["Элеонора", "Изольда", "Матильда", "Розалинда"],
    epithet: "Королевство Вестмарк",
  },
  {
    id: 1,
    name: "Огры",
    plural: "огров",
    color: "#a3512e",
    might: 1.6,
    cunning: 0.2,
    fertility: 0.85,
    industry: 0.7,
    aggression: 0.85,
    leaderNames: ["Громм", "Ургаш", "Дробокост", "Хрящ", "Молотоглав", "Багрок"],
    princessNames: ["Урга", "Громха", "Кроша", "Багра"],
    epithet: "Орда Костяных Холмов",
  },
  {
    id: 2,
    name: "Эльфы",
    plural: "эльфов",
    color: "#5e9e6f",
    might: 0.9,
    cunning: 0.95,
    fertility: 0.7,
    industry: 1.0,
    aggression: 0.2,
    leaderNames: ["Аэлантир", "Финвэль", "Кэлориан", "Тариэль", "Люмендил", "Сильварас"],
    princessNames: ["Аэривель", "Лиантэль", "Нимуэ", "Эстелла"],
    epithet: "Вечный Лес Атенвейл",
  },
  {
    id: 3,
    name: "Тёмные эльфы",
    plural: "тёмных эльфов",
    color: "#7d5ba6",
    might: 1.1,
    cunning: 0.9,
    fertility: 0.7,
    industry: 0.9,
    aggression: 0.65,
    leaderNames: ["Вельзарин", "Мортрис", "Ксандрет", "Нокстар", "Драэвин", "Зерафель"],
    princessNames: ["Вирса", "Нериэль", "Мальвия", "Ксандра"],
    epithet: "Подземный Двор Нирвет",
  },
  {
    id: 4,
    name: "Гномы",
    plural: "гномов",
    color: "#b0762f",
    might: 1.2,
    cunning: 0.5,
    fertility: 0.8,
    industry: 1.4,
    aggression: 0.4,
    leaderNames: ["Торгрим", "Балдур", "Кромдор", "Фундин", "Даргин", "Стурла"],
    princessNames: ["Хельга", "Брунна", "Дагмара", "Торвия"],
    epithet: "Твердыня Карак-Дум",
  },
  {
    id: 5,
    name: "Орки",
    plural: "орков",
    color: "#6f8a3d",
    might: 1.35,
    cunning: 0.35,
    fertility: 1.3,
    industry: 0.6,
    aggression: 0.8,
    leaderNames: ["Гхазкул", "Морглум", "Уртаг", "Крагаш", "Задрыг", "Вааргх"],
    princessNames: ["Гримка", "Уруша", "Заглатка", "Морда"],
    epithet: "Вааагх Красной Луны",
  },
  {
    id: 6,
    name: "Нежить",
    plural: "нежити",
    color: "#8f9aa8",
    might: 1.15,
    cunning: 0.6,
    fertility: 0.5,
    industry: 0.8,
    aggression: 0.7,
    leaderNames: ["Некрозар", "Владмор", "Костеслав", "Мортивус", "Тленорий", "Гниллиан"],
    princessNames: ["Морвена", "Лихелла", "Тлена", "Прахея"],
    epithet: "Империя Вечной Ночи",
  },
  {
    id: 7,
    name: "Народ Глубин",
    plural: "народа глубин",
    color: "#3d7f9e",
    might: 0.95,
    cunning: 0.75,
    fertility: 1.0,
    industry: 1.15,
    aggression: 0.3,
    leaderNames: ["Тхалассор", "Кораллион", "Абиссар", "Приливник", "Нереус", "Глубомир"],
    princessNames: ["Мареана", "Жемчужина", "Тхалия", "Уна"],
    epithet: "Царство Изумрудной Бездны",
  },
  {
    id: 8,
    name: "Зверолюды",
    plural: "зверолюдов",
    color: "#8a6a4f",
    might: 1.25,
    cunning: 0.4,
    fertility: 1.2,
    industry: 0.65,
    aggression: 0.7,
    leaderNames: ["Рогволд", "Клыкан", "Шерстомор", "Копытень", "Вожак Гар", "Рыкош"],
    princessNames: ["Лапка", "Гривна", "Рыся", "Волчица Ая"],
    epithet: "Дикие Пустоши Ара-Тан",
  },
  {
    id: 9,
    name: "Драконорождённые",
    plural: "драконорождённых",
    color: "#b03a3a",
    might: 1.5,
    cunning: 0.65,
    fertility: 0.6,
    industry: 0.95,
    aggression: 0.55,
    leaderNames: ["Азгарот", "Вермитракс", "Игнис", "Пеплокрыл", "Драковар", "Смаугрин"],
    princessNames: ["Эмбера", "Искра", "Вирмия", "Пламелла"],
    epithet: "Пепельный Доминион",
  },
]
